version: '3'

services:
  web:
    build: .
    container_name: flask-devops
    ports:
      - "5000:5000"

    volumes:
      - app-data:/app

    networks:
      - devops-network

volumes:
  app-data:

networks:
  devops-network: